parameters:
    lexty_flashy.storageKey: lexty_flashy
    lexty_flashy.type: info
    lexty_flashy.delay: 2800

services:
    lexty_flashy.twig_extension:
        class: Lexty\FlashyBundle\Twig\FlashyExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    lexty_flashy.flashy:
        class: Lexty\FlashyBundle\Flashy
        arguments: [@session, '%lexty_flashy.storageKey%', '%lexty_flashy.type%', '%lexty_flashy.delay%']
